### PR TITLE
Feature camera access

### PR DESCRIPTION
**Pull request by AliceDmitrieva**
https://trello.com/c/QJEYVymE/1-getting-access-to-the-camera
https://trello.com/c/gHPSMbpP/5-set-autofocus-to-camera

### CODE REVIEW

**Comment by oxied** [comment]
Add links on Trello tasks into description, which were done in this PR.

And also put link on this PR into these Trello tasks, please.

**Comment by AliceDmitrieva** [comment]
https://trello.com/c/QJEYVymE/1-getting-access-to-the-camera
https://trello.com/c/gHPSMbpP/5-set-autofocus-to-camera

**Comment by AliceDmitrieva** [comment]
@oxied Done

**Comment by oxied** [comment]
Looks good.

**Pull request merged**
